"""Shared bounds and fixed errors for the local-agent application modules."""

from __future__ import annotations

import re


AGENT_CONTRACT_VERSION = "local-agent.v9"
MAX_SESSIONS = 12
MAX_EVENTS = 4_000
MAX_STEPS_PER_TURN = 16
MAX_TOOL_RESULT_CHARS = 24_000
MAX_FILE_READ_BYTES = 96_000
MAX_FILE_WRITE_BYTES = 256_000
MAX_LIST_ENTRIES = 400
MAX_DISCOVERY_FILES = 400
MAX_GIT_STATUS_ENTRIES = 400
MAX_WORKSPACE_TRANSACTION_FILES = 8
MAX_WORKSPACE_TRANSACTION_BYTES = 1_024_000
MAX_WORKSPACE_TRANSACTION_DIFF_CHARS = 240_000
MAX_TREE_SCAN_ENTRIES = 20_000
MAX_SEARCH_RESULTS = 80
WORKSPACE_INSPECTION_VERSION = "workspace-inspection.v2"
WORKSPACE_WRITE_VERSION = "workspace-publication.v1"
MAX_SEARCH_QUERY_CHARS = 1_024
MAX_SEARCH_FILE_BYTES = 2_000_000
MAX_SEARCH_TOTAL_BYTES = 16_000_000
MAX_SEARCH_DEPTH = 32
MAX_WORKSPACE_SCAN_SECONDS = 5.0
MAX_REGEX_MATCH_SECONDS = 0.05
MAX_DIFF_CHARS = 60_000
MAX_REVIEWABLE_COMMAND_CHARS = 4_000
MAX_TOOL_CALLS_PER_REPLY = 8
MAX_TOOL_NAME_CHARS = 128
MAX_CALL_ID_CHARS = 256
MAX_HISTORY_MESSAGES = 60
OLD_TOOL_RESULT_KEEP_CHARS = 2_000
MAX_EVENT_PAGE = 500
MAX_COMMAND_SECONDS = 600
DEFAULT_COMMAND_SECONDS = 120
APPROVAL_WAIT_SECONDS = 1_800
MAX_ASSISTANT_TEXT_CHARS = 120_000
MAX_AGENT_STREAM_BYTES = 2_000_000
STREAM_EVENT_CHARS = 192
MAX_STREAM_DELTA_EVENTS = 2_000
STREAM_WAIT_SECONDS = 15.0
SKIP_DIRS = frozenset(
    {
        ".git",
        "node_modules",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        "dist",
        "build",
        ".next",
        ".cache",
    }
)
ID_PATTERN = re.compile(r"^[0-9a-f]{32}$")


class LocalAgentError(ValueError):
    """Typed local-agent rejection whose code is safe for an HTTP response."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


__all__ = (
    "AGENT_CONTRACT_VERSION",
    "APPROVAL_WAIT_SECONDS",
    "DEFAULT_COMMAND_SECONDS",
    "ID_PATTERN",
    "LocalAgentError",
    "MAX_AGENT_STREAM_BYTES",
    "MAX_ASSISTANT_TEXT_CHARS",
    "MAX_CALL_ID_CHARS",
    "MAX_COMMAND_SECONDS",
    "MAX_DIFF_CHARS",
    "MAX_DISCOVERY_FILES",
    "MAX_EVENTS",
    "MAX_EVENT_PAGE",
    "MAX_FILE_READ_BYTES",
    "MAX_FILE_WRITE_BYTES",
    "MAX_HISTORY_MESSAGES",
    "MAX_GIT_STATUS_ENTRIES",
    "MAX_WORKSPACE_TRANSACTION_BYTES",
    "MAX_WORKSPACE_TRANSACTION_DIFF_CHARS",
    "MAX_WORKSPACE_TRANSACTION_FILES",
    "MAX_LIST_ENTRIES",
    "MAX_REVIEWABLE_COMMAND_CHARS",
    "MAX_SEARCH_RESULTS",
    "MAX_SEARCH_QUERY_CHARS",
    "MAX_SEARCH_FILE_BYTES",
    "MAX_SEARCH_TOTAL_BYTES",
    "MAX_SEARCH_DEPTH",
    "MAX_WORKSPACE_SCAN_SECONDS",
    "MAX_REGEX_MATCH_SECONDS",
    "WORKSPACE_INSPECTION_VERSION",
    "MAX_SESSIONS",
    "MAX_STEPS_PER_TURN",
    "MAX_STREAM_DELTA_EVENTS",
    "MAX_TOOL_CALLS_PER_REPLY",
    "MAX_TOOL_NAME_CHARS",
    "MAX_TOOL_RESULT_CHARS",
    "MAX_TREE_SCAN_ENTRIES",
    "OLD_TOOL_RESULT_KEEP_CHARS",
    "SKIP_DIRS",
    "STREAM_EVENT_CHARS",
    "STREAM_WAIT_SECONDS",
)
