export function syntheticMcpRegistryServerReview() {
  return {
    contract_version: "mcp-registry-server-review.v1",
    source: {
      registry: "official_mcp_registry",
      base_url: "https://registry.modelcontextprotocol.io",
      fetched_at: "2026-08-29T12:00:00Z",
      delivery: "live",
      cache_age_seconds: 0,
    },
    server: {
      catalog_id: "a".repeat(32),
      presentation_revision: "f".repeat(64),
      name: "com.example/synthetic-files",
      title: "Synthetic Files",
      description: "Inspect fictional example files through MCP.",
      publisher: "com.example",
      version: "1.2.3",
      status: "active",
      updated_at: "2026-08-28T10:20:30Z",
      repository_url: "https://github.com/example/synthetic-files",
      website_url: "https://example.com/synthetic-files",
      icon: null,
      packages: [{
        registry_type: "npm",
        identifier: "@example/synthetic-files",
        version: "1.2.3",
        transport: "stdio",
        runtime_hint: "npx",
        checksum_available: true,
      }],
      remotes: [],
      supports_local: true,
      supports_remote: false,
      management_state: "not_managed",
      install_action: "unavailable",
      install_reason: "guarded_install_host_not_implemented",
    },
    provenance: {
      registry: "official_mcp_registry",
      registry_membership_security_review: "not_claimed",
      publisher_namespace: "com.example",
      repository_url: "https://github.com/example/synthetic-files",
      repository_source: "github",
      repository_identity_declared: true,
      repository_subfolder_declared: false,
      website_url: "https://example.com/synthetic-files",
      schema_url: "https://static.modelcontextprotocol.io/schemas/example/server.schema.json",
      license_state: "not_declared_by_registry_contract",
    },
    versions: [{
      version: "1.2.3",
      status: "active",
      updated_at: "2026-08-28T10:20:30Z",
      selected: true,
    }],
    version_history_state: "live",
    options: [{
      option_id: "b".repeat(32),
      kind: "local_package",
      label: "NPM package",
      registry_type: "npm",
      package_identifier: "@example/synthetic-files",
      package_version: "1.2.3",
      runtime_hint: "npx",
      transport: "stdio",
      endpoint_host: null,
      endpoint_state: "not_applicable",
      secure_transport: null,
      checksum_state: "declared",
      requirements: [{
        requirement_id: "c".repeat(32),
        location: "environment_variable",
        name: "EXAMPLE_TOKEN",
        description: "A fictional access token.",
        required: true,
        secret: true,
        format: "string",
        repeated: false,
        fixed_value_declared: false,
        default_declared: false,
        choices_count: 0,
        user_value_needed: true,
      }],
      risks: ["downloads_package", "executes_local_code", "credential_input_declared"],
      compatibility: {
        status: "requires_configuration",
        reasons: [
          "known_package_registry",
          "supported_transport",
          "configuration_required",
          "machine_runtime_not_probed",
          "platform_not_declared",
          "mcp_handshake_not_performed",
        ],
        platform_compatibility: "unverified",
        runtime_availability: "unverified",
        mcp_handshake: "not_performed",
      },
      execution_state: "preview_only",
    }],
    plan_revision: "d".repeat(64),
    partial: false,
    management_state: "not_managed",
    install_action: "unavailable",
    uninstall_action: "not_applicable",
    review_truth: "preview_only_no_install_or_connection_authority",
  };
}
