import type { TextAnalysisResearchCatalog } from "./contracts";

const ADDITIONAL_SYNTHETIC_METRICS = [
  ["problem_evidence_quality", "Problem evidence quality", "prompt", "Does a diagnosis state observed and expected behavior, reproduction, and environment?"],
  ["context_sufficiency", "Context sufficiency", "prompt", "Are component, current state, environment, and boundaries stated?"],
  ["ambiguity_resolution", "Ambiguity resolution", "prompt", "Are material vague references clarified or explicitly replaced?"],
  ["constraint_precision", "Constraint precision", "prompt", "Are relevant constraints concrete and bounded?"],
  ["acceptance_testability", "Acceptance testability", "prompt", "Can important outcomes be checked with observable pass conditions?"],
  ["deliverable_contract", "Deliverable contract", "prompt", "Is the requested artifact or interface explicit?"],
  ["exploration_conversion", "Exploration conversion", "collaboration", "Does exploration converge to an observable plan, decision, or check?"],
  ["scope_change_discipline", "Scope-change discipline", "collaboration", "Are scope changes acknowledged and incorporated?"],
  ["rework_candidate_rate", "Rework-candidate rate", "collaboration", "How often does feedback indicate possible misunderstanding or avoidable repetition?"],
  ["decomposition_coverage", "Decomposition coverage", "logic", "Are active requirements represented in the observable plan?"],
  ["hypothesis_test_linkage", "Hypothesis-to-test linkage", "logic", "Is each technical hypothesis followed by a discriminating check?"],
  ["decision_rationale", "Decision rationale", "logic", "Are consequential choices linked to constraints, alternatives, or evidence?"],
  ["open_loop_closure", "Open-loop closure", "agent_answer", "Are questions and deferred decisions closed or carried forward?"],
  ["verification_strategy", "Verification strategy", "agent_answer", "Does the plan connect requirements to suitable verification?"],
  ["first_pass_verification", "First-pass verification", "outcome", "Did the first meaningful executable verification pass?"],
] as const;

/** Fictional product-state preview; model identities and papers are public metadata. */
export const SYNTHETIC_TEXT_ANALYSIS_RESEARCH = {
  catalog_key: "text-analysis-methods",
  catalog_version: 4,
  reviewed_on: "2040-01-03",
  privacy_mode: "local_only_redacted_content",
  summary_policy: "multidimensional_profile_no_universal_score",
  catalog_read_starts_session_access: false,
  catalog_read_downloads_models: false,
  methods: [
    {
      key: "deterministic_structure",
      name: "Deterministic structure cues",
      family: "extraction",
      approach: "rules",
      maturity: "product_baseline",
      privacy_tier: "redacted_content",
      purpose: "Find explicit goals, constraints and outcomes with explainable local rules.",
      produces: ["structure receipts", "coverage"],
      candidate_model_keys: [],
      source_keys: ["rope"],
      limitations: ["Lexical cues do not prove clarity or correctness."],
    },
    {
      key: "multilingual_embeddings",
      name: "Multilingual semantic retrieval",
      family: "linking",
      approach: "embedding",
      maturity: "evaluated_exploratory",
      privacy_tier: "redacted_content",
      purpose: "Link paraphrased requirements, actions and evidence across languages.",
      produces: ["candidate links", "retrieval coverage"],
      candidate_model_keys: ["multilingual_e5_small", "multilingual_e5_base", "qwen3_embedding_06b"],
      source_keys: ["e5_model", "e5_base_model", "qwen_embedding"],
      limitations: ["Similarity is not correctness or entailment."],
    },
    {
      key: "scoped_nli",
      name: "Scoped entailment and contradiction",
      family: "semantic_inference",
      approach: "nli",
      maturity: "failed_gate",
      privacy_tier: "redacted_content",
      purpose: "Test whether linked statements agree, conflict or remain unrelated.",
      produces: ["contradiction candidates", "abstentions"],
      candidate_model_keys: ["mdeberta_xnli"],
      source_keys: ["mdeberta_model"],
      limitations: ["The current candidate failed the different-scope false-positive gate."],
    },
    {
      key: "traceability_graph",
      name: "Requirement-action-evidence graph",
      family: "workflow",
      approach: "graph",
      maturity: "research_candidate",
      privacy_tier: "redacted_content",
      purpose: "Connect request, plan, action, verification and outcome.",
      produces: ["traceability coverage", "open loops"],
      candidate_model_keys: [],
      source_keys: ["rope"],
      limitations: ["Chronology alone cannot establish a valid edge."],
    },
  ],
  model_candidates: [
    {
      key: "multilingual_e5_small",
      display_name: "Multilingual E5 small",
      repository_id: "intfloat/multilingual-e5-small",
      task: "semantic retrieval",
      license_spdx: "MIT",
      revision: "614241f622f53c4eeff9890bdc4f31cfecc418b3",
      parameter_scale: "118M",
      language_scope: "multilingual including English and Polish",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Promising synthetic retrieval result; private calibration remains required.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.666667,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.819444,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["e5_model"],
    },
    {
      key: "multilingual_e5_base",
      display_name: "Multilingual E5 base",
      repository_id: "intfloat/multilingual-e5-base",
      task: "semantic retrieval",
      license_spdx: "MIT",
      revision: "d128750597153bb5987e10b1c3493a34e5a4502a",
      parameter_scale: "278M",
      language_scope: "multilingual including English and Polish",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Led the tiny fictional retrieval screen; disabled pending representative private calibration.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.833333,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.902778,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["e5_base_model"],
    },
    {
      key: "mdeberta_xnli",
      display_name: "mDeBERTa multilingual NLI",
      repository_id: "MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7",
      task: "scoped NLI",
      license_spdx: "MIT",
      revision: "b5113eb38ab63efdd7f280f8c144ea8b13f978ce",
      parameter_scale: "278M",
      language_scope: "multilingual including English and Polish",
      status: "rejected_screen",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Rejected after a 100% different-scope false-positive rate.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 18,
        primary_metric: "three_way_accuracy",
        primary_value: 0.555556,
        secondary_metric: "macro_f1",
        secondary_value: 0.6,
        critical_metric: "different_scope_false_positive_rate",
        critical_value: 1,
      },
      source_keys: ["mdeberta_model"],
    },
    {
      key: "qwen3_embedding_06b",
      display_name: "Qwen3 Embedding 0.6B",
      repository_id: "Qwen/Qwen3-Embedding-0.6B",
      task: "instruction-aware semantic retrieval",
      license_spdx: "Apache-2.0",
      revision: "97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3",
      parameter_scale: "0.6B",
      language_scope: "100+ languages",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Best fictional retrieval result; private calibration remains required.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.75,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.861111,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["qwen_embedding"],
    },
    {
      key: "bge_m3",
      display_name: "BGE-M3",
      repository_id: "BAAI/bge-m3",
      task: "hybrid semantic retrieval",
      license_spdx: "MIT",
      revision: "142964af7e05de16511657561de8e8750fc153a0",
      parameter_scale: "568M",
      language_scope: "100+ languages",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "The safe pin beat BM25 but trailed E5 base and Qwen on the tiny full screen; it remains disabled.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.666667,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.819444,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["bge_m3"],
    },
    {
      key: "bge_reranker_v2_m3",
      display_name: "BGE reranker v2 M3",
      repository_id: "BAAI/bge-reranker-v2-m3",
      task: "multilingual reranking",
      license_spdx: "Apache-2.0",
      revision: "953dc6f6f85a1b2dbfca4c34a2796e7dde08d41e",
      parameter_scale: "568M",
      language_scope: "multilingual",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Promising full-screen reranking with smoke/full variance; disabled pending calibration.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.75,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.875,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["bge_reranker"],
    },
    {
      key: "qwen3_reranker_06b",
      display_name: "Qwen3 Reranker 0.6B",
      repository_id: "Qwen/Qwen3-Reranker-0.6B",
      task: "instruction-aware reranking",
      license_spdx: "Apache-2.0",
      revision: "e61197ed45024b0ed8a2d74b80b4d909f1255473",
      parameter_scale: "0.6B",
      language_scope: "100+ languages",
      status: "evaluated_exploratory",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Improved over the lexical full screen but remains uncalibrated and disabled.",
      benchmark: {
        benchmark_key: "bilingual-model-screen-v1-full",
        case_count: 12,
        primary_metric: "top1_accuracy",
        primary_value: 0.666667,
        secondary_metric: "mean_reciprocal_rank",
        secondary_value: 0.826389,
        critical_metric: null,
        critical_value: null,
      },
      source_keys: ["qwen_reranker"],
    },
    {
      key: "qwen3_4b_rubric",
      display_name: "Qwen3 4B Instruct 2507",
      repository_id: "Qwen/Qwen3-4B-Instruct-2507",
      task: "structured local rubric",
      license_spdx: "Apache-2.0",
      revision: "cdbee75f17c01a7cc42f958dc650907174af0554",
      parameter_scale: "4B",
      language_scope: "100+ languages and dialects",
      status: "rejected_screen",
      product_enabled: false,
      trust_remote_code: false,
      decision: "Rejected for scoring because accuracy and abstention behavior missed the gates.",
      benchmark: {
        benchmark_key: "bilingual-rubric-screen-v1-full",
        case_count: 24,
        primary_metric: "exact_label_accuracy",
        primary_value: 0.666667,
        secondary_metric: "json_schema_compliance_rate",
        secondary_value: 1,
        critical_metric: "abstention_macro_f1",
        critical_value: 0.521368,
      },
      source_keys: ["qwen_rubric"],
    },
  ],
  metric_roadmap: [
    {
      key: "task_definition",
      name: "Task definition",
      profile: "prompt",
      question: "Does the request state the action, target, context and desired outcome?",
      direction: "higher_is_better",
      state: "baseline_available",
      evidence: "Typed request fields with content-free detection receipts.",
      method_keys: ["deterministic_structure"],
      caution: "Measures stated structure, not whether the task is wise.",
    },
    {
      key: "clarification_value",
      name: "Clarification value",
      profile: "collaboration",
      question: "Do questions resolve material uncertainty rather than merely increase count?",
      direction: "contextual",
      state: "research",
      evidence: "Question acts linked to ambiguity, answer and decision.",
      method_keys: ["traceability_graph"],
      caution: "Question frequency alone is not a quality signal.",
    },
    {
      key: "requirement_action_traceability",
      name: "Requirement-to-action traceability",
      profile: "logic",
      question: "Can each active requirement be linked to implementation or deferral?",
      direction: "higher_is_better",
      state: "research",
      evidence: "Semantic retrieval plus typed graph edges.",
      method_keys: ["multilingual_embeddings", "traceability_graph"],
      caution: "Links remain candidates until calibrated or reviewed.",
    },
    {
      key: "agent_answer_grounding",
      name: "Agent answer grounding",
      profile: "agent_answer",
      question: "Are important claims supported by tool, test, source or artifact evidence?",
      direction: "higher_is_better",
      state: "needs_objective_evidence",
      evidence: "Claim-to-evidence links with evidence type and outcome.",
      method_keys: ["traceability_graph"],
      caution: "Agent self-report never counts as proof.",
    },
    {
      key: "verified_delivery",
      name: "Verified delivery",
      profile: "outcome",
      question: "Did the requested artifact pass relevant executable checks or acceptance?",
      direction: "higher_is_better",
      state: "needs_objective_evidence",
      evidence: "Versioned verification or human-acceptance evidence.",
      method_keys: ["traceability_graph"],
      caution: "Completion text is never sufficient.",
    },
    ...ADDITIONAL_SYNTHETIC_METRICS.map(([key, name, profile, question]) => ({
      key,
      name,
      profile,
      question,
      direction: key === "rework_candidate_rate" ? "lower_is_better" as const : "higher_is_better" as const,
      state: ["problem_evidence_quality", "context_sufficiency"].includes(key)
        ? "baseline_available" as const
        : key === "first_pass_verification"
          ? "needs_objective_evidence" as const
          : "research" as const,
      evidence: "Versioned content-free receipts with explicit applicability and coverage.",
      method_keys: ["traceability_graph"],
      caution: "Missing or unsupported evidence remains Unknown or Abstained, never zero.",
    })),
  ],
  sources: [
    {
      key: "rope",
      title: "Requirement-Oriented Prompt Engineering",
      url: "https://arxiv.org/abs/2409.08775",
      kind: "paper",
    },
    {
      key: "e5_model",
      title: "multilingual-e5-small model card",
      url: "https://huggingface.co/intfloat/multilingual-e5-small",
      kind: "model_card",
    },
    {
      key: "e5_base_model",
      title: "multilingual-e5-base model card",
      url: "https://huggingface.co/intfloat/multilingual-e5-base",
      kind: "model_card",
    },
    {
      key: "mdeberta_model",
      title: "mDeBERTa multilingual NLI model card",
      url: "https://huggingface.co/MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7",
      kind: "model_card",
    },
    {
      key: "qwen_embedding",
      title: "Qwen3 Embedding 0.6B model card",
      url: "https://huggingface.co/Qwen/Qwen3-Embedding-0.6B",
      kind: "model_card",
    },
    {
      key: "bge_m3",
      title: "BGE-M3 model card",
      url: "https://huggingface.co/BAAI/bge-m3",
      kind: "model_card",
    },
    {
      key: "bge_reranker",
      title: "BGE reranker v2 M3 model card",
      url: "https://huggingface.co/BAAI/bge-reranker-v2-m3",
      kind: "model_card",
    },
    {
      key: "qwen_reranker",
      title: "Qwen3 Reranker 0.6B model card",
      url: "https://huggingface.co/Qwen/Qwen3-Reranker-0.6B",
      kind: "model_card",
    },
    {
      key: "qwen_rubric",
      title: "Qwen3 4B Instruct 2507 model card",
      url: "https://huggingface.co/Qwen/Qwen3-4B-Instruct-2507",
      kind: "model_card",
    },
  ],
} satisfies TextAnalysisResearchCatalog;
