"""Tokenize every literal colour in the dashboard CSS and derive dark-theme counterparts (OKLCH).

Light values stay exactly as they were (defined once as CSS variables); the dark
block is generated by inverting lightness in OKLCH while keeping hue, with
hand-curated overrides for the core shell tokens in theme.css.
"""
from __future__ import annotations

import math
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1] / "src"
FILES = [ROOT / "styles.css", ROOT / "shared/ui/primitives.css", *sorted((ROOT / "features").rglob("*.css"))]
PALETTE = ROOT / "app/palette.generated.css"

HEX = re.compile(r"(?<![\w&])#([0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{4}|[0-9a-fA-F]{3})\b")
RGBA = re.compile(r"\brgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*(0?\.\d+|1(?:\.0+)?|0))?\s*\)")


# ---------- colour math (sRGB <-> OKLCH) ----------

def srgb_to_linear(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_to_srgb(c: float) -> float:
    c = max(0.0, min(1.0, c))
    return 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


def rgb_to_oklch(r: int, g: int, b: int) -> tuple[float, float, float]:
    lr, lg, lb = (srgb_to_linear(v / 255) for v in (r, g, b))
    l = 0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb
    m = 0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb
    s = 0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb
    l_, m_, s_ = (math.copysign(abs(v) ** (1 / 3), v) for v in (l, m, s))
    L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_
    C = math.hypot(a, bb)
    h = math.degrees(math.atan2(bb, a)) % 360
    return L, C, h


def oklch_to_rgb(L: float, C: float, h: float) -> tuple[int, int, int] | None:
    a = C * math.cos(math.radians(h))
    bb = C * math.sin(math.radians(h))
    l_ = L + 0.3963377774 * a + 0.2158037573 * bb
    m_ = L - 0.1055613458 * a - 0.0638541728 * bb
    s_ = L - 0.0894841775 * a - 1.2914855480 * bb
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    lr = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    lg = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    lb = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
    if min(lr, lg, lb) < -0.002 or max(lr, lg, lb) > 1.002:
        return None
    return tuple(round(linear_to_srgb(v) * 255) for v in (lr, lg, lb))  # type: ignore[return-value]


def to_gamut(L: float, C: float, h: float) -> tuple[int, int, int]:
    for _ in range(40):
        rgb = oklch_to_rgb(L, C, h)
        if rgb is not None:
            return rgb
        C *= 0.9
    rgb = oklch_to_rgb(L, 0.0, h)
    return rgb or (0, 0, 0)


def dark_counterpart(r: int, g: int, b: int) -> tuple[int, int, int]:
    """Invert lightness with a curve that keeps dark UIs from going pitch black or washing out."""

    L, C, h = rgb_to_oklch(r, g, b)
    if L >= 0.985 and C < 0.01:          # pure white surfaces -> elevated dark surface
        L2, C2 = 0.24, 0.012
        h = 230
    elif L >= 0.80:                        # light tints (chip / panel backgrounds) -> muted dark tints
        L2 = 0.22 + (0.985 - L) * 0.6     # 0.985 -> 0.22, 0.80 -> 0.33
        C2 = min(C * 0.75, 0.06)
    elif L >= 0.55:                        # borders, soft fills, mid greys
        L2 = 0.36 + (0.80 - L) * 1.2      # 0.80 -> 0.36, 0.55 -> 0.66
        C2 = min(C * 0.9, 0.08)
    else:                                  # inks / strong accents -> light, slightly more vivid
        L2 = 0.70 + (0.55 - L) * 0.5      # 0.55 -> 0.70, 0.10 -> 0.925, 0 -> 0.975
        C2 = min(C * 1.1, 0.17)
    return to_gamut(L2, C2, h)


def hex6(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


# ---------- harvest ----------

def expand_hex(raw: str) -> tuple[int, int, int, float | None]:
    raw = raw.lower()
    if len(raw) in (3, 4):
        raw = "".join(ch * 2 for ch in raw)
    r, g, b = int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16)
    alpha = int(raw[6:8], 16) / 255 if len(raw) == 8 else None
    return r, g, b, alpha


styles = (ROOT / "styles.css").read_text(encoding="utf-8")
root_start = styles.index(":root {")
root_end = styles.index("}", root_start)
root_block = styles[root_start:root_end]
core: dict[str, str] = {}
for name, value in re.findall(r"--([a-z0-9-]+):\s*([^;]+);", root_block):
    core.setdefault(name, value.strip())
value_to_token: dict[str, str] = {}
for name, value in core.items():
    m = HEX.fullmatch(value)
    if m:
        r, g, b, _ = expand_hex(m.group(1))
        value_to_token.setdefault(hex6(r, g, b), name)

solid: dict[str, tuple[int, int, int]] = {}          # var name -> rgb
alphas: dict[str, tuple[int, int, int, float]] = {}  # var name -> rgba


def alpha_name(r: int, g: int, b: int, a: float) -> str:
    return f"pa-{r}-{g}-{b}-{int(round(a * 1000))}"


def replace_hex(m: re.Match[str]) -> str:
    r, g, b, alpha = expand_hex(m.group(1))
    if alpha is not None:
        name = alpha_name(r, g, b, alpha)
        alphas[name] = (r, g, b, alpha)
        return f"var(--{name})"
    key = hex6(r, g, b)
    token = value_to_token.get(key)
    if token:
        return f"var(--{token})"
    name = f"p-{key[1:]}"
    solid[name] = (r, g, b)
    return f"var(--{name})"


def replace_rgba(m: re.Match[str]) -> str:
    r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
    a = float(m.group(4)) if m.group(4) is not None else 1.0
    if a >= 1.0:
        key = hex6(r, g, b)
        token = value_to_token.get(key)
        if token:
            return f"var(--{token})"
        name = f"p-{key[1:]}"
        solid[name] = (r, g, b)
        return f"var(--{name})"
    name = alpha_name(r, g, b, a)
    alphas[name] = (r, g, b, a)
    return f"var(--{name})"


def convert(text: str) -> str:
    text = RGBA.sub(replace_rgba, text)
    text = HEX.sub(replace_hex, text)
    return text


changed = 0
for path in FILES:
    text = path.read_text(encoding="utf-8")
    if path.name == "styles.css":
        head, block, tail = text[:root_start], text[root_start:root_end], text[root_end:]
        new = head + block + convert(tail)
    else:
        new = convert(text)
    if new != text:
        path.write_text(new, encoding="utf-8")
        changed += 1
print("files changed:", changed, "| solid vars:", len(solid), "| alpha vars:", len(alphas))

# ---------- generate palette.generated.css ----------

DARK_SURFACE_BASE = (21, 28, 36)      # matches --surface in the dark theme
DARK_CANVAS_BASE = (11, 16, 22)

light_lines = []
dark_lines = []
# Colours used by the sidebar family are already a dark design; keep them as designed in dark mode.
styles_now = (ROOT / "styles.css").read_text(encoding="utf-8")
pinned: set[str] = set()
for line in styles_now.splitlines():
    if re.match(r"^\.(sidebar|brand|primary-nav|nav-indicator|privacy-status)", line):
        pinned.update(re.findall(r"var\(--(p-[0-9a-f]{6}|pa-[0-9-]+)\)", line))
shared = {name for name in pinned if styles_now.count(f"var(--{name})") > sum(line.count(f"var(--{name})") for line in styles_now.splitlines() if re.match(r"^\.(sidebar|brand|primary-nav|nav-indicator|privacy-status)", line))}
print("pinned sidebar vars:", len(pinned), "| also used elsewhere:", sorted(shared))

for name, (r, g, b) in sorted(solid.items()):
    light_lines.append(f"  --{name}: {hex6(r, g, b)};")
    if name in pinned:
        dark_lines.append(f"  --{name}: {hex6(r, g, b)};")
    else:
        dark_lines.append(f"  --{name}: {hex6(*dark_counterpart(r, g, b))};")
for name, (r, g, b, a) in sorted(alphas.items()):
    light_lines.append(f"  --{name}: rgba({r}, {g}, {b}, {a:g});")
    L, C, _ = rgb_to_oklch(r, g, b)
    if name in pinned:
        dark_lines.append(f"  --{name}: rgba({r}, {g}, {b}, {a:g});")
    elif L >= 0.93 and C < 0.03 and a >= 0.45:
        # frosted white panels -> dark surface overlays, same opacity
        dr, dg, db = DARK_SURFACE_BASE
        dark_lines.append(f"  --{name}: rgba({dr}, {dg}, {db}, {a:g});")
    elif L >= 0.93 and C < 0.03:
        # faint white highlights stay highlights
        dark_lines.append(f"  --{name}: rgba(255, 255, 255, {a:g});")
    elif L <= 0.35:
        # shadows / dark scrims -> darker and a little stronger
        dark_lines.append(f"  --{name}: rgba(0, 0, 0, {min(1.0, a * 1.7):g});")
    else:
        # coloured glows / tints keep their hue; slightly brighter on dark
        L2, C2, h2 = rgb_to_oklch(r, g, b)
        dr, dg, db = to_gamut(min(0.82, L2 + 0.12), C2, h2)
        dark_lines.append(f"  --{name}: rgba({dr}, {dg}, {db}, {min(1.0, a * 1.15):g});")

PALETTE.write_text(
    "/* Generated by scratchpad/make_theme.py - every literal colour of the dashboard CSS as a variable.\n"
    "   Light values are the original literals; dark values are OKLCH lightness inversions (hue kept),\n"
    "   with the core shell tokens hand-tuned in theme.css. Regenerate instead of editing by hand. */\n\n"
    ":root {\n" + "\n".join(light_lines) + "\n}\n\n"
    ":root[data-theme=\"dark\"] {\n" + "\n".join(dark_lines) + "\n}\n",
    encoding="utf-8",
)
print("palette written:", PALETTE)
