"""Reviewable, metadata-only task discovery application boundary."""

from .contracts import (
    AcceptCandidate,
    CandidateIdFactory,
    CandidateIdentity,
    DiscoveryBatch,
    DiscoveryBoundary,
    DiscoverySignal,
    DiscoverySignalStrategy,
    MergeCandidates,
    RejectCandidate,
    RejectionReason,
    SignalDirection,
    SplitCandidate,
    TaskCandidate,
    TaskCategory,
    TaskDecisionCommand,
    TaskDecisionKind,
    TaskDecisionService,
)
from .engine import (
    CandidateIdError,
    DiscoveryConfig,
    DiscoveryError,
    InvalidDiscoveryInputError,
    TaskDiscoveryEngine,
)
from .review import (
    CandidateNotFoundError,
    InvalidTaskReviewError,
    ReviewArtifactIdFactory,
    StaleCandidateError,
    TaskReviewConflictError,
    TaskReviewError,
    TaskReviewResult,
    TaskReviewService,
)
from .signals import (
    DEFAULT_DISCOVERY_STRATEGIES,
    TemporalProximityStrategy,
    TerminalContinuityStrategy,
)
from .storage import (
    DiscoveryFingerprintFactory,
    DiscoveryPersistenceService,
    DiscoveryPersistResult,
    DiscoveryStorageConflictError,
)

__all__ = [
    "AcceptCandidate",
    "CandidateIdError",
    "CandidateIdFactory",
    "CandidateNotFoundError",
    "CandidateIdentity",
    "DEFAULT_DISCOVERY_STRATEGIES",
    "DiscoveryBatch",
    "DiscoveryBoundary",
    "DiscoveryConfig",
    "DiscoveryError",
    "DiscoveryFingerprintFactory",
    "DiscoveryPersistenceService",
    "DiscoveryPersistResult",
    "DiscoverySignal",
    "DiscoverySignalStrategy",
    "DiscoveryStorageConflictError",
    "InvalidDiscoveryInputError",
    "InvalidTaskReviewError",
    "MergeCandidates",
    "RejectCandidate",
    "RejectionReason",
    "ReviewArtifactIdFactory",
    "SignalDirection",
    "SplitCandidate",
    "StaleCandidateError",
    "TaskCandidate",
    "TaskCategory",
    "TaskDecisionCommand",
    "TaskDecisionKind",
    "TaskDecisionService",
    "TaskDiscoveryEngine",
    "TaskReviewConflictError",
    "TaskReviewError",
    "TaskReviewResult",
    "TaskReviewService",
    "TemporalProximityStrategy",
    "TerminalContinuityStrategy",
]
