import { afterEach, describe, expect, it, vi } from "vitest";

import {
  SYNTHETIC_DIRECT_TRANSFER_OPT_IN,
  grantSyntheticDirectTransfer,
  issueSyntheticVerifiedPrincipal,
} from "./directTransferProtocol";
import {
  createSyntheticByteSource,
  createSyntheticDirectTransferSession,
  type SyntheticByteSource,
} from "./directTransferSession";

async function preparedSession({
  createdAt = Date.now(),
  expiresAt = createdAt + 60_000,
}: { createdAt?: number; expiresAt?: number } = {}) {
  const owner = issueSyntheticVerifiedPrincipal("owner");
  const recipient = issueSyntheticVerifiedPrincipal("recipient");
  const ownerGrant = grantSyntheticDirectTransfer(owner, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
  const recipientGrant = grantSyntheticDirectTransfer(recipient, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
  const session = await createSyntheticDirectTransferSession({
    ownerGrant,
    recipientGrant,
    source: createSyntheticByteSource(64 * 1024, 31),
    createdAt,
    expiresAt,
  });
  return { session, ownerGrant, recipientGrant };
}

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

class FailedDirectChannel extends EventTarget {
  readonly label = "prompt-enhancer-direct-file-v1";
  readonly protocol = "browser-direct-file.v1";
  readonly ordered = true;
  readonly maxPacketLifeTime = null;
  readonly maxRetransmits = null;
  binaryType: BinaryType = "arraybuffer";
  readyState: RTCDataChannelState = "connecting";
  bufferedAmount = 0;
  bufferedAmountLowThreshold = 0;

  close(): void {
    if (this.readyState === "closed") return;
    this.readyState = "closed";
    this.dispatchEvent(new Event("close"));
  }

  send(): void {
    throw new Error("failed synthetic path cannot send");
  }
}

class FailedDirectPeer extends EventTarget {
  static configurations: RTCConfiguration[] = [];
  static nextPeer = 0;

  readonly peerIndex: number;
  iceGatheringState: RTCIceGatheringState = "complete";
  connectionState: RTCPeerConnectionState = "failed";
  iceConnectionState: RTCIceConnectionState = "failed";
  localDescription: RTCSessionDescription | null = null;
  readonly sctp = { maxMessageSize: 65_535 } as RTCSctpTransport;

  constructor(configuration: RTCConfiguration) {
    super();
    this.peerIndex = FailedDirectPeer.nextPeer;
    FailedDirectPeer.nextPeer += 1;
    FailedDirectPeer.configurations.push(configuration);
  }

  createDataChannel(): RTCDataChannel {
    return new FailedDirectChannel() as unknown as RTCDataChannel;
  }

  async createOffer(): Promise<RTCSessionDescriptionInit> {
    return { type: "offer", sdp: "v=0\r\n" };
  }

  async createAnswer(): Promise<RTCSessionDescriptionInit> {
    return { type: "answer", sdp: "v=0\r\n" };
  }

  async setLocalDescription(description: RTCSessionDescriptionInit): Promise<void> {
    this.localDescription = description as RTCSessionDescription;
  }

  async setRemoteDescription(): Promise<void> {
    if (this.peerIndex !== 1) return;
    const event = new Event("datachannel") as RTCDataChannelEvent;
    Object.defineProperty(event, "channel", { value: new FailedDirectChannel() });
    this.dispatchEvent(event);
  }

  close(): void {
    this.connectionState = "closed";
  }
}

class RelayCandidatePeer extends FailedDirectPeer {
  override async setLocalDescription(description: RTCSessionDescriptionInit): Promise<void> {
    await super.setLocalDescription(description);
    const event = new Event("icecandidate") as RTCPeerConnectionIceEvent;
    Object.defineProperty(event, "candidate", {
      value: { type: "relay", candidate: "candidate:1 1 udp 1 192.0.2.10 5000 typ relay" },
    });
    this.dispatchEvent(event);
  }
}

describe("synthetic direct-transfer authorization and lifecycle", () => {
  it("keeps generated bytes behind a content-free, one-shot source capability", async () => {
    const owner = issueSyntheticVerifiedPrincipal("owner");
    const recipient = issueSyntheticVerifiedPrincipal("recipient");
    const ownerGrant = grantSyntheticDirectTransfer(owner, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
    const recipientGrant = grantSyntheticDirectTransfer(recipient, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
    const source = createSyntheticByteSource(257, 7);
    expect(JSON.parse(JSON.stringify(source))).toEqual({
      kind: "generated_synthetic_bytes",
      fictional: true,
      byteLength: 257,
    });
    const session = await createSyntheticDirectTransferSession({ ownerGrant, recipientGrant, source });
    await expect(createSyntheticDirectTransferSession({ ownerGrant, recipientGrant, source })).rejects.toMatchObject({
      reason: "authorization_unavailable",
    });
    session.close();
  });

  it("rejects caller-owned bytes instead of accepting them as a session source", async () => {
    const owner = issueSyntheticVerifiedPrincipal("owner");
    const recipient = issueSyntheticVerifiedPrincipal("recipient");
    const ownerGrant = grantSyntheticDirectTransfer(owner, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
    const recipientGrant = grantSyntheticDirectTransfer(recipient, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
    await expect(createSyntheticDirectTransferSession({
      ownerGrant,
      recipientGrant,
      source: new Uint8Array([1, 2, 3]) as unknown as SyntheticByteSource,
    })).rejects.toMatchObject({ reason: "authorization_unavailable" });
  });

  it("requires recipient consent before per-transfer owner approval", async () => {
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    expect(session.getStatus()).toMatchObject({
      state: "awaiting_recipient_consent",
      recipientConsented: false,
      ownerApproved: false,
    });
    expect(() => session.approve(ownerGrant)).toThrowError(expect.objectContaining({ reason: "consent_required" }));
    session.consent(recipientGrant);
    expect(session.getStatus().state).toBe("awaiting_owner_approval");
    session.approve(ownerGrant);
    expect(session.getStatus()).toMatchObject({
      state: "negotiating_direct",
      recipientConsented: true,
      ownerApproved: true,
      relayUsed: false,
      cloudBytesUsed: false,
      persistedPayload: false,
    });
    session.close();
  });

  it("lets owner revocation fence negotiation and never claims recall", async () => {
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    session.consent(recipientGrant);
    session.approve(ownerGrant);
    expect(session.revoke(ownerGrant)).toBe(true);
    expect(session.getStatus()).toMatchObject({
      state: "revoked",
      remoteRecallGuaranteed: false,
      bytesSent: 0,
      bytesReceived: 0,
    });
    expect(() => session.start(ownerGrant, recipientGrant)).toThrowError(
      expect.objectContaining({ reason: "revoked_before_completion" }),
    );
    expect(session.revoke(ownerGrant)).toBe(false);
  });

  it("lets expiry win after approval but before negotiation", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(2_000);
    const { session, ownerGrant, recipientGrant } = await preparedSession({ createdAt: 1_000, expiresAt: 10_000 });
    session.consent(recipientGrant);
    session.approve(ownerGrant);
    vi.setSystemTime(10_000);
    expect(() => session.start(ownerGrant, recipientGrant)).toThrowError(
      expect.objectContaining({ reason: "expired" }),
    );
    expect(session.getStatus()).toMatchObject({ state: "expired", failureReason: null });
  });

  it("rejects a grant issued to the wrong synthetic role for every action", async () => {
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    expect(() => session.consent(ownerGrant)).toThrowError(expect.objectContaining({ reason: "authorization_unavailable" }));
    session.consent(recipientGrant);
    expect(() => session.approve(recipientGrant)).toThrowError(expect.objectContaining({ reason: "authorization_unavailable" }));
    session.close();
  });

  it("reports a missing browser peer API without pretending to diagnose NAT", async () => {
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    session.consent(recipientGrant);
    session.approve(ownerGrant);
    vi.stubGlobal("RTCPeerConnection", undefined);
    await expect(session.start(ownerGrant, recipientGrant)).rejects.toMatchObject({
      reason: "browser_webrtc_unavailable",
    });
    expect(session.getStatus()).toMatchObject({
      state: "failed",
      failureReason: "browser_webrtc_unavailable",
      reachabilityHint: null,
    });
    session.close();
  });

  it("fails a peer-connection path explicitly with no relay and only a possible-topology hint", async () => {
    FailedDirectPeer.configurations = [];
    FailedDirectPeer.nextPeer = 0;
    vi.stubGlobal("RTCPeerConnection", FailedDirectPeer as unknown as typeof RTCPeerConnection);
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    session.consent(recipientGrant);
    session.approve(ownerGrant);
    await expect(session.start(ownerGrant, recipientGrant)).rejects.toMatchObject({
      reason: "unreachable_no_relay",
    });
    expect(session.getStatus()).toMatchObject({
      state: "failed",
      failureReason: "unreachable_no_relay",
      reachabilityHint: "symmetric_nat_or_cgnat_or_firewall_possible",
      relayUsed: false,
      cloudBytesUsed: false,
    });
    expect(FailedDirectPeer.configurations).toHaveLength(2);
    for (const configuration of FailedDirectPeer.configurations) {
      expect(configuration.iceServers).toEqual([]);
      expect(configuration.iceCandidatePoolSize).toBe(0);
    }
    session.close();
  });

  it("rejects a relay candidate immediately and never relabels it as a NAT failure", async () => {
    FailedDirectPeer.configurations = [];
    FailedDirectPeer.nextPeer = 0;
    vi.stubGlobal("RTCPeerConnection", RelayCandidatePeer as unknown as typeof RTCPeerConnection);
    const { session, ownerGrant, recipientGrant } = await preparedSession();
    session.consent(recipientGrant);
    session.approve(ownerGrant);
    await expect(session.start(ownerGrant, recipientGrant)).rejects.toMatchObject({
      reason: "relay_candidate_rejected",
    });
    expect(session.getStatus()).toMatchObject({
      state: "failed",
      failureReason: "relay_candidate_rejected",
      reachabilityHint: null,
      relayUsed: false,
      cloudBytesUsed: false,
    });
    session.close();
  });
});
