import { useEffect, useRef, useState } from "react";

import {
  SOCIAL_SYNTHETIC_PRINCIPAL_ID,
  type SocialSnapshot,
} from "../../../shared/api/socialHub";
import {
  SYNTHETIC_DIRECT_TRANSFER_OPT_IN,
  DirectTransferProtocolError,
  grantSyntheticDirectTransfer,
  issueSyntheticVerifiedPrincipal,
  type DirectTransferFailureReason,
  type DirectTransferStatus,
  type SyntheticDirectTransferGrant,
} from "./directTransferProtocol";
import {
  createSyntheticByteSource,
  createSyntheticDirectTransferSession,
  type SyntheticDirectTransferSessionPort,
} from "./directTransferSession";

const SYNTHETIC_DEMO_BYTES = 2 * 1024 * 1024 + 137;

export function syntheticDirectTransferPrototypeIsAvailable({
  snapshot,
  development = import.meta.env.DEV,
  buildOptIn = import.meta.env.VITE_SOCIAL_DIRECT_FILE_PROTOTYPE,
}: {
  snapshot: Pick<SocialSnapshot, "origin" | "fictional" | "principal_id">;
  development?: boolean;
  buildOptIn?: string;
}): boolean {
  return development
    && buildOptIn === SYNTHETIC_DIRECT_TRANSFER_OPT_IN
    && snapshot.origin === "synthetic_fixture"
    && snapshot.fictional === true
    && snapshot.principal_id === SOCIAL_SYNTHETIC_PRINCIPAL_ID;
}

interface PrototypeRuntime {
  readonly session: SyntheticDirectTransferSessionPort;
  readonly ownerGrant: SyntheticDirectTransferGrant;
  readonly recipientGrant: SyntheticDirectTransferGrant;
  readonly unsubscribe: () => void;
}

const ERROR_COPY: Readonly<Record<DirectTransferFailureReason, string>> = {
  authorization_unavailable: "Synthetic authorization is unavailable.",
  consent_required: "Synthetic recipient consent is required.",
  owner_approval_required: "Per-transfer synthetic owner approval is required.",
  expired: "The synthetic transfer expired.",
  revoked_before_completion: "The synthetic transfer was revoked before completion.",
  crypto_unavailable: "The browser SHA-256 implementation is unavailable.",
  browser_webrtc_unavailable: "This browser does not provide the required WebRTC peer API.",
  backpressure_timeout: "The direct channel remained congested beyond the bounded wait.",
  invalid_manifest: "The synthetic integrity manifest was rejected.",
  invalid_range: "The requested synthetic byte ranges were rejected.",
  protocol_invalid: "The direct-transfer protocol validation failed.",
  relay_candidate_rejected: "A relay candidate was rejected by the direct-only policy.",
  integrity_failed: "Received bytes did not match the integrity manifest.",
  unreachable_no_relay: "No direct path was established and no relay fallback exists.",
  channel_closed: "The direct browser channel closed before completion.",
};

function safeErrorCopy(caught: unknown, fallback: string): string {
  return caught instanceof DirectTransferProtocolError ? ERROR_COPY[caught.reason] : fallback;
}

const STATE_LABELS: Readonly<Record<DirectTransferStatus["state"], string>> = {
  awaiting_recipient_consent: "Awaiting explicit synthetic-recipient consent",
  awaiting_owner_approval: "Awaiting per-transfer synthetic-owner approval",
  negotiating_direct: "Approved · ready for ephemeral direct negotiation",
  direct_ready: "Direct browser data channel ready",
  transferring: "Transferring generated bytes peer to peer",
  paused: "Paused · no new frames are being queued",
  verifying: "Verifying chunk, whole-file, and Merkle commitments",
  completed: "Complete · integrity verified",
  revoked: "Revoked · future bytes stopped; received bytes cannot be recalled",
  expired: "Expired · transfer fenced",
  failed: "Stopped · no direct path or protocol validation failed",
};

function percentage(status: DirectTransferStatus): number {
  if (status.byteSize <= 0) return 0;
  return Math.min(100, Math.round((status.bytesReceived / status.byteSize) * 100));
}

function canRevoke(state: DirectTransferStatus["state"]): boolean {
  return state !== "completed" && state !== "revoked" && state !== "expired" && state !== "failed";
}

function disposeRuntime(current: PrototypeRuntime | null): void {
  if (current === null) return;
  try {
    current.unsubscribe();
  } finally {
    current.session.close();
  }
}

/**
 * An opt-in lab, never a real file picker. It creates two in-page browser peers
 * and transfers deterministic generated bytes so the actual protocol can be
 * exercised without a real identity, filename, path, or user payload.
 */
export function DirectTransferPrototypePanel({ snapshot }: { snapshot: SocialSnapshot }) {
  const available = syntheticDirectTransferPrototypeIsAvailable({ snapshot });
  const [acknowledged, setAcknowledged] = useState(false);
  const [status, setStatus] = useState<DirectTransferStatus | null>(null);
  const [preparing, setPreparing] = useState(false);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");
  const runtime = useRef<PrototypeRuntime | null>(null);
  const mounted = useRef(true);
  const startGenerationRef = useRef(0);

  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      startGenerationRef.current += 1;
      disposeRuntime(runtime.current);
      runtime.current = null;
    };
  }, []);

  if (!available) return null;

  const prepare = async () => {
    if (!acknowledged || preparing || runtime.current !== null) return;
    setPreparing(true);
    setError("");
    try {
      const owner = issueSyntheticVerifiedPrincipal("owner");
      const recipient = issueSyntheticVerifiedPrincipal("recipient");
      const ownerGrant = grantSyntheticDirectTransfer(owner, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const recipientGrant = grantSyntheticDirectTransfer(recipient, SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const createdAt = Date.now();
      const session = await createSyntheticDirectTransferSession({
        ownerGrant,
        recipientGrant,
        source: createSyntheticByteSource(SYNTHETIC_DEMO_BYTES),
        createdAt,
        expiresAt: createdAt + 10 * 60 * 1_000,
      });
      if (!mounted.current) {
        session.close();
        return;
      }
      const unsubscribe = session.subscribe(setStatus);
      runtime.current = { session, ownerGrant, recipientGrant, unsubscribe };
    } catch (caught) {
      if (mounted.current) setError(safeErrorCopy(caught, "Prototype preparation failed closed."));
    } finally {
      if (mounted.current) setPreparing(false);
    }
  };

  const consent = () => {
    try {
      runtime.current?.session.consent(runtime.current.recipientGrant);
    } catch (caught) {
      setError(safeErrorCopy(caught, "Synthetic consent failed closed."));
    }
  };

  const approve = () => {
    try {
      runtime.current?.session.approve(runtime.current.ownerGrant);
    } catch (caught) {
      setError(safeErrorCopy(caught, "Synthetic approval failed closed."));
    }
  };

  const start = async () => {
    const current = runtime.current;
    if (current === null || running) return;
    const generation = startGenerationRef.current + 1;
    startGenerationRef.current = generation;
    const isCurrent = () => (
      mounted.current
      && runtime.current === current
      && startGenerationRef.current === generation
    );
    setRunning(true);
    setError("");
    try {
      await current.session.start(current.ownerGrant, current.recipientGrant);
    } catch (caught) {
      if (isCurrent()) setError(safeErrorCopy(caught, "Direct transfer failed closed."));
    } finally {
      if (isCurrent()) setRunning(false);
    }
  };

  const ownerAction = (action: "pause" | "resume" | "revoke") => {
    const current = runtime.current;
    if (current === null) return;
    try {
      if (action === "pause") current.session.pause(current.ownerGrant);
      if (action === "resume") current.session.resume(current.ownerGrant);
      if (action === "revoke") current.session.revoke(current.ownerGrant);
    } catch (caught) {
      setError(safeErrorCopy(caught, "The requested owner action failed closed."));
    }
  };

  const closeResult = () => {
    const current = runtime.current;
    startGenerationRef.current += 1;
    runtime.current = null;
    try {
      disposeRuntime(current);
    } finally {
      setStatus(null);
      setError("");
      setPreparing(false);
      setRunning(false);
    }
  };

  return (
    <section aria-label="Synthetic WebRTC direct-transfer lab" className="social-direct-prototype">
      <div className="social-direct-prototype__heading">
        <div>
          <p className="eyebrow">Exact opt-in · synthetic fixture only</p>
          <h4>Browser data-channel transfer lab</h4>
        </div>
        <strong>Development prototype</strong>
      </div>
      <p>
        This isolated lab transfers 2 MiB of generated fixture bytes between two in-page browser peers.
        It reads no file, has no filename or path, uses no signaling server, byte server, STUN, TURN, relay,
        or cloud byte fallback, and does not authenticate a real person. Browser-standard DTLS protects the
        hop, but this is not a production E2EE or identity claim.
      </p>
      <label className="social-direct-prototype__acknowledgement">
        <input
          checked={acknowledged}
          disabled={runtime.current !== null}
          onChange={(event) => setAcknowledged(event.currentTarget.checked)}
          type="checkbox"
        />
        <span>I understand this moves generated synthetic bytes only and cannot be used for a real file.</span>
      </label>
      {status === null ? (
        <button
          className="button button--primary"
          disabled={!acknowledged || preparing}
          onClick={() => void prepare()}
          type="button"
        >
          {preparing ? "Preparing SHA-256 manifest…" : "Prepare synthetic transfer"}
        </button>
      ) : (
        <div className="social-direct-prototype__status" aria-live="polite">
          <strong>{STATE_LABELS[status.state]}</strong>
          <progress
            aria-label="Synthetic direct-transfer progress"
            max={status.byteSize}
            value={status.bytesReceived}
          />
          <span>{percentage(status)}% · {status.bytesReceived.toLocaleString()} of {status.byteSize.toLocaleString()} generated bytes received locally</span>
          <div className="social-direct-prototype__actions">
            {status.state === "awaiting_recipient_consent" ? (
              <button className="button button--secondary" onClick={consent} type="button">Grant synthetic recipient consent</button>
            ) : null}
            {status.state === "awaiting_owner_approval" ? (
              <button className="button button--secondary" onClick={approve} type="button">Approve this transfer as synthetic owner</button>
            ) : null}
            {status.state === "negotiating_direct" ? (
              <button className="button button--primary" disabled={running} onClick={() => void start()} type="button">Start direct two-peer transfer</button>
            ) : null}
            {status.state === "transferring" ? (
              <button className="button button--secondary" onClick={() => ownerAction("pause")} type="button">Pause direct transfer</button>
            ) : null}
            {status.state === "paused" ? (
              <button className="button button--secondary" onClick={() => ownerAction("resume")} type="button">Resume direct transfer</button>
            ) : null}
            {canRevoke(status.state) ? (
              <button className="button button--danger" onClick={() => ownerAction("revoke")} type="button">Revoke before completion</button>
            ) : null}
            {!canRevoke(status.state) ? (
              <button className="button button--secondary" onClick={closeResult} type="button">Close result</button>
            ) : null}
          </div>
          {status.failureReason === "unreachable_no_relay" ? (
            <span role="alert">No direct path. Symmetric NAT, CGNAT, or a firewall may be the cause; no relay fallback exists.</span>
          ) : null}
        </div>
      )}
      {error !== "" ? <p role="alert">Stopped safely: {error}</p> : null}
      <ul className="social-direct-prototype__facts">
        <li>Recipient consent and per-transfer owner approval are separate fences.</li>
        <li>Pause stops new frames; already buffered frames may settle. Resume rechecks expiry and revocation.</li>
        <li>Completion requires every chunk digest, the whole-file SHA-256, and the domain-separated Merkle root.</li>
        <li>Revocation stops future bytes; it cannot recall bytes already received.</li>
      </ul>
    </section>
  );
}
