import { expect, test, type Page } from "@playwright/test";
const FIXTURE = "/e2e/fixtures/agent-message-search.html";
async function open(page: Page) { await page.goto(FIXTURE); await expect(page.getByRole("button", { name: "Search saved messages", exact: true })).toBeVisible(); }
async function dialog(page: Page) { await page.getByRole("button", { name: "Search saved messages", exact: true }).click(); return page.getByRole("dialog", { name: "Search saved messages", exact: true }); }
async function effects(page: Page) { for (const name of ["Create", "Send", "Resume", "Activate"]) await expect(page.locator("html")).toHaveAttribute(`data-message-search-${name.toLowerCase()}`, "0"); }
test.describe("saved-message search", () => {
  test("finds an exact retained early event through paged sparse history and jumps without starting work", async ({ page }) => { await open(page); const d = await dialog(page); const conversation = page.getByRole("region", { name: "Agent conversation", exact: true }); await expect(d.getByLabel("Saved-message phrase")).toBeFocused(); await d.getByLabel("Saved-message phrase").fill("early match"); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); const row = d.getByRole("button", { name: /Retained synthetic chat/ }); await expect(row).toContainText("Synthetic early match outside the default window."); await expect(conversation.getByText("Synthetic early match outside the default window.", { exact: true })).toHaveCount(0); await row.click(); await expect(conversation.getByText("Synthetic early match outside the default window.", { exact: true })).toBeVisible(); await expect(page.locator("html")).toHaveAttribute("data-message-search-retained-reads", "3"); await effects(page); });
  test("renders HTML-like excerpts as plaintext and gates archived matches independently", async ({ page }) => { await open(page); const d = await dialog(page); await d.getByLabel("Saved-message phrase").fill("HTML-like"); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d.getByText("A synthetic <b>HTML-like</b> retained answer.", { exact: true })).toBeVisible(); await d.getByLabel("Saved-message phrase").fill("archived"); await d.getByLabel("Current project").check(); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d).toContainText("No retained saved message matches"); await d.getByLabel("All projects").check(); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d).toContainText("No retained saved message matches"); await d.getByLabel("Include archived chats").check(); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d).toContainText("Archived synthetic chat"); await effects(page); });
  test("reports a bounded failure and retries the same search", async ({ page }) => { await open(page); const d = await dialog(page); await d.getByLabel("Saved-message phrase").fill("failure"); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d.getByRole("alert")).toContainText("current results are unchanged"); await d.getByRole("button", { name: "Retry search", exact: true }).click(); await expect(d).toContainText("matching chats loaded"); await effects(page); });
  test("keeps snapshot pagination bounded", async ({ page }) => { await open(page); const d = await dialog(page); await d.getByLabel("Saved-message phrase").fill("pagination"); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await expect(d).toContainText("20 of 21 matching chats loaded"); await d.getByRole("button", { name: "Load more matches", exact: true }).click(); await expect(d).toContainText("21 of 21 matching chats loaded"); await effects(page); });
  test("invalidates stale work and Escape aborts it without losing the draft", async ({ page }) => { await open(page); const composer = page.getByRole("textbox", { name: "Message to the agent", exact: true }); await composer.fill("synthetic unsent draft"); const d = await dialog(page); await d.getByLabel("Saved-message phrase").fill("slow"); await d.getByRole("button", { name: "Search saved messages", exact: true }).click(); await d.press("Escape"); await expect(d).toHaveCount(0); await expect(composer).toHaveValue("synthetic unsent draft"); await expect(page.locator("html")).toHaveAttribute("data-message-search-slow-abort", "1"); await expect(page.locator("html")).toHaveAttribute("data-message-search-slow-late", "1"); await expect(page.getByText("Synthetic retained event 2.", { exact: true })).toHaveCount(0); expect(await page.evaluate(() => `${localStorage.getItem("agent-message-search")}${sessionStorage.getItem("agent-message-search")}`)).not.toContain("slow"); await effects(page); });
  for (const viewport of [{ width: 1280, height: 900 }, { width: 390, height: 844 }]) test(`keeps dialog and composer usable at ${viewport.width}px`, async ({ page }) => { await page.setViewportSize(viewport); await open(page); const d = await dialog(page); await expect(d).toBeVisible(); await expect(page.getByRole("textbox", { name: "Message to the agent", exact: true })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
});
