import { expect, test } from "@playwright/test";

test.describe("synthetic direct-only WebRTC prototype", () => {
  test("moves generated bytes between two browser peers with consent, approval, pause/resume, and integrity", async ({ page }) => {
    const consoleMessages: string[] = [];
    page.on("console", (message) => consoleMessages.push(message.text()));
    await page.goto("/social");

    const lab = page.getByRole("region", { name: "Synthetic WebRTC direct-transfer lab" });
    await expect(lab).toBeVisible();
    await expect(lab).toContainText("uses no signaling server, byte server, STUN, TURN, relay");
    await expect(page.locator("input[type='file']")).toHaveCount(0);

    const persistedBefore = await page.evaluate(async () => ({
      local: Object.keys(localStorage),
      session: Object.keys(sessionStorage),
      databases: "databases" in indexedDB ? (await indexedDB.databases()).map((entry) => entry.name ?? "") : [],
    }));

    await lab.getByRole("checkbox").check();
    await lab.getByRole("button", { name: "Prepare synthetic transfer" }).click();
    await expect(lab).toContainText("Awaiting explicit synthetic-recipient consent");
    await lab.getByRole("button", { name: "Grant synthetic recipient consent" }).click();
    await expect(lab).toContainText("Awaiting per-transfer synthetic-owner approval");
    await lab.getByRole("button", { name: "Approve this transfer as synthetic owner" }).click();
    await expect(lab).toContainText("Approved · ready for ephemeral direct negotiation");
    await lab.getByRole("button", { name: "Start direct two-peer transfer" }).click();

    const pause = lab.getByRole("button", { name: "Pause direct transfer" });
    await expect(pause).toBeVisible({ timeout: 20_000 });
    await pause.click();
    await expect(lab).toContainText("Paused · no new frames are being queued");
    await lab.getByRole("button", { name: "Resume direct transfer" }).click();
    await expect(lab).toContainText("Complete · integrity verified", { timeout: 30_000 });
    await expect(lab.getByRole("progressbar")).toHaveAttribute("value", "2097289");
    await expect(lab).toContainText("100%");
    await expect(lab).toContainText("Revocation stops future bytes; it cannot recall bytes already received.");
    await expect(lab.getByRole("alert")).toHaveCount(0);

    const persistedAfter = await page.evaluate(async () => ({
      local: Object.keys(localStorage),
      session: Object.keys(sessionStorage),
      databases: "databases" in indexedDB ? (await indexedDB.databases()).map((entry) => entry.name ?? "") : [],
      remoteResources: performance.getEntriesByType("resource")
        .map((entry) => new URL(entry.name).origin)
        .filter((origin) => origin !== location.origin),
    }));
    expect(persistedAfter).toEqual({ ...persistedBefore, remoteResources: [] });
    expect(consoleMessages.join("\n")).not.toMatch(/candidate|session.description|typ relay|generated bytes:|file(name|path)|local path/iu);
  });

  test("lets owner revocation win before negotiation and states that recall is not guaranteed", async ({ page }) => {
    await page.goto("/social");
    const lab = page.getByRole("region", { name: "Synthetic WebRTC direct-transfer lab" });
    await lab.getByRole("checkbox").check();
    await lab.getByRole("button", { name: "Prepare synthetic transfer" }).click();
    await expect(lab).toContainText("Awaiting explicit synthetic-recipient consent");
    await lab.getByRole("button", { name: "Grant synthetic recipient consent" }).click();
    await lab.getByRole("button", { name: "Approve this transfer as synthetic owner" }).click();
    await lab.getByRole("button", { name: "Revoke before completion" }).click();
    await expect(lab).toContainText("Revoked · future bytes stopped; received bytes cannot be recalled");
    await expect(lab.getByRole("button", { name: "Start direct two-peer transfer" })).toHaveCount(0);
    await expect(page.locator("input[type='file']")).toHaveCount(0);
  });

  test("releases a paused sender immediately when the owner revokes", async ({ page }) => {
    await page.goto("/social");
    const lab = page.getByRole("region", { name: "Synthetic WebRTC direct-transfer lab" });
    await lab.getByRole("checkbox").check();
    await lab.getByRole("button", { name: "Prepare synthetic transfer" }).click();
    await lab.getByRole("button", { name: "Grant synthetic recipient consent" }).click();
    await lab.getByRole("button", { name: "Approve this transfer as synthetic owner" }).click();
    await lab.getByRole("button", { name: "Start direct two-peer transfer" }).click();
    await lab.getByRole("button", { name: "Pause direct transfer" }).click();
    await expect(lab).toContainText("Paused · no new frames are being queued");
    await lab.getByRole("button", { name: "Revoke before completion" }).click();
    await expect(lab).toContainText("Revoked · future bytes stopped; received bytes cannot be recalled");
    await expect(lab).toContainText("The synthetic transfer was revoked before completion.", { timeout: 5_000 });
    await expect(lab.getByRole("button", { name: "Resume direct transfer" })).toHaveCount(0);
  });

  test("distinguishes a missing browser peer API from a failed direct path", async ({ page }) => {
    await page.goto("/social");
    const result = await page.evaluate(async () => {
      const protocol = await import("/src/features/social/directTransfer/directTransferProtocol.ts");
      const runtime = await import("/src/features/social/directTransfer/directTransferSession.ts");
      const owner = protocol.issueSyntheticVerifiedPrincipal("owner");
      const recipient = protocol.issueSyntheticVerifiedPrincipal("recipient");
      const ownerGrant = protocol.grantSyntheticDirectTransfer(owner, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const recipientGrant = protocol.grantSyntheticDirectTransfer(recipient, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const session = await runtime.createSyntheticDirectTransferSession({
        ownerGrant,
        recipientGrant,
        source: runtime.createSyntheticByteSource(65_536, 41),
      });
      session.consent(recipientGrant);
      session.approve(ownerGrant);
      const descriptor = Object.getOwnPropertyDescriptor(globalThis, "RTCPeerConnection");
      Object.defineProperty(globalThis, "RTCPeerConnection", { configurable: true, value: undefined });
      let reason = "";
      try {
        await session.start(ownerGrant, recipientGrant);
      } catch (error) {
        reason = error instanceof protocol.DirectTransferProtocolError ? error.reason : "unexpected";
      } finally {
        if (descriptor !== undefined) Object.defineProperty(globalThis, "RTCPeerConnection", descriptor);
        session.close();
      }
      return { reason, status: session.getStatus() };
    });
    expect(result).toMatchObject({
      reason: "browser_webrtc_unavailable",
      status: {
        state: "failed",
        failureReason: "browser_webrtc_unavailable",
        reachabilityHint: null,
        relayUsed: false,
        cloudBytesUsed: false,
        persistedPayload: false,
      },
    });
  });

  test("keeps revocation authoritative when it arrives at the verification boundary", async ({ page }) => {
    await page.goto("/social");
    const result = await page.evaluate(async () => {
      const protocol = await import("/src/features/social/directTransfer/directTransferProtocol.ts");
      const runtime = await import("/src/features/social/directTransfer/directTransferSession.ts");
      const owner = protocol.issueSyntheticVerifiedPrincipal("owner");
      const recipient = protocol.issueSyntheticVerifiedPrincipal("recipient");
      const ownerGrant = protocol.grantSyntheticDirectTransfer(owner, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const recipientGrant = protocol.grantSyntheticDirectTransfer(recipient, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const session = await runtime.createSyntheticDirectTransferSession({
        ownerGrant,
        recipientGrant,
        source: runtime.createSyntheticByteSource(262_281, 43),
      });
      const states: string[] = [];
      session.subscribe((status) => {
        states.push(status.state);
        if (status.state === "verifying") session.revoke(ownerGrant);
      });
      session.consent(recipientGrant);
      session.approve(ownerGrant);
      let reason = "";
      try {
        await session.start(ownerGrant, recipientGrant);
      } catch (error) {
        reason = error instanceof protocol.DirectTransferProtocolError ? error.reason : "unexpected";
      }
      const status = session.getStatus();
      session.close();
      return { reason, states, status };
    });
    expect(result.reason).toBe("revoked_before_completion");
    expect(result.states).toContain("verifying");
    expect(result.states).toContain("revoked");
    expect(result.states).not.toContain("completed");
    expect(result.status).toMatchObject({ state: "revoked", remoteRecallGuaranteed: false });
  });

  test("does not advance to transferring after a direct-ready revocation", async ({ page }) => {
    await page.goto("/social");
    const result = await page.evaluate(async () => {
      const protocol = await import("/src/features/social/directTransfer/directTransferProtocol.ts");
      const runtime = await import("/src/features/social/directTransfer/directTransferSession.ts");
      const owner = protocol.issueSyntheticVerifiedPrincipal("owner");
      const recipient = protocol.issueSyntheticVerifiedPrincipal("recipient");
      const ownerGrant = protocol.grantSyntheticDirectTransfer(owner, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const recipientGrant = protocol.grantSyntheticDirectTransfer(recipient, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
      const session = await runtime.createSyntheticDirectTransferSession({
        ownerGrant,
        recipientGrant,
        source: runtime.createSyntheticByteSource(65_537, 47),
      });
      const states: string[] = [];
      session.subscribe((status) => {
        states.push(status.state);
        if (status.state === "direct_ready") session.revoke(ownerGrant);
      });
      session.consent(recipientGrant);
      session.approve(ownerGrant);
      let reason = "";
      try {
        await session.start(ownerGrant, recipientGrant);
      } catch (error) {
        reason = error instanceof protocol.DirectTransferProtocolError ? error.reason : "unexpected";
      }
      const status = session.getStatus();
      session.close();
      return { reason, states, status };
    });
    expect(result.reason).toBe("revoked_before_completion");
    expect(result.states).toContain("direct_ready");
    expect(result.states).toContain("revoked");
    expect(result.states).not.toContain("transferring");
    expect(result.status.state).toBe("revoked");
  });

  test("does not publish completion when expiry arrives at the verification boundary", async ({ page }) => {
    await page.goto("/social");
    const result = await page.evaluate(async () => {
      const protocol = await import("/src/features/social/directTransfer/directTransferProtocol.ts");
      const runtime = await import("/src/features/social/directTransfer/directTransferSession.ts");
      const originalNow = Date.now;
      let now = 1_000;
      Date.now = () => now;
      try {
        const owner = protocol.issueSyntheticVerifiedPrincipal("owner");
        const recipient = protocol.issueSyntheticVerifiedPrincipal("recipient");
        const ownerGrant = protocol.grantSyntheticDirectTransfer(owner, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
        const recipientGrant = protocol.grantSyntheticDirectTransfer(recipient, protocol.SYNTHETIC_DIRECT_TRANSFER_OPT_IN);
        const session = await runtime.createSyntheticDirectTransferSession({
          ownerGrant,
          recipientGrant,
          source: runtime.createSyntheticByteSource(262_281, 53),
          createdAt: 1_000,
          expiresAt: 10_000,
        });
        const states: string[] = [];
        session.subscribe((status) => {
          states.push(status.state);
          if (status.state === "verifying") now = 10_000;
        });
        session.consent(recipientGrant);
        session.approve(ownerGrant);
        let reason = "";
        try {
          await session.start(ownerGrant, recipientGrant);
        } catch (error) {
          reason = error instanceof protocol.DirectTransferProtocolError ? error.reason : "unexpected";
        }
        const status = session.getStatus();
        session.close();
        return { reason, states, status };
      } finally {
        Date.now = originalNow;
      }
    });
    expect(result.reason).toBe("expired");
    expect(result.states).toContain("verifying");
    expect(result.states).toContain("expired");
    expect(result.states).not.toContain("completed");
    expect(result.status.state).toBe("expired");
  });
});
